server:
  port: 8080
spring:
  #DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  #JPA
  jpa:
    show-sql: true
 #   hibernate:
 #     ddl-auto: create-drop
  thymeleaf:
    mode: HTML5 # 使用HTML5标准
    cache: false # 热部署静态文件,禁止使用缓存
    encoding: UTF-8
  h2:
    console:
      enabled: true #打开缓存数据库H2的控制台